### PR TITLE
Stop using deprecated _MM_GET_EXCEPTION_STATE

### LINKED ISSUE #4419: `_MM_GET_EXCEPTION_STATE` is deprecated
```
error: use of deprecated function `core::arch::x86_64::_MM_GET_EXCEPTION_STATE`: see `_mm_getcsr` documentation - use inline assembly instead
  --> oak_restricted_kernel/src/interrupts.rs:24:56
   |
24 |             _MM_EXCEPT_OVERFLOW, _MM_EXCEPT_UNDERFLOW, _MM_GET_EXCEPTION_STATE,
   |                                                        ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D deprecated` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(deprecated)]`
```

I am ignoring this in #4404 but we should clean it up.

### PR DESCRIPTION
**Pull request by conradgrobler**
Fixes #4419

### CODE REVIEW

File: oak_restricted_kernel/src/interrupts.rs [hunk 1]
```diff
@@ -296,27 +286,13 @@ extern "x86-interrupt" fn machine_check_handler(stack_frame: InterruptStackFrame
     shutdown::shutdown();
 }
 
-bitflags! {
```
Comment (andrisaar) [inline oak_restricted_kernel/src/interrupts.rs:299]: Please don't :)

I created this bitfield so that the error flags would be easily readable. Could you replace them with the constant values?

Comment (conradgrobler) [reply oak_restricted_kernel/src/interrupts.rs]: Done.

File: oak_restricted_kernel/src/interrupts.rs [hunk 2]
```diff
@@ -300,12 +294,12 @@ bitflags! {
     #[repr(transparent)]
     #[derive(Debug)]
     pub struct Mxcsr: u32 {
```
Comment (andrisaar) [inline oak_restricted_kernel/src/interrupts.rs:296]: I should really have taken a closer look; `x86_64::registers::mxcsr::MxCsr` _already is_ a bitflag, so printing it out would have done the right thing!

Sorry about that. Feel free to drop this wrapper, as the other bitflag is good enough.

**Review by andrisaar — APPROVED** [review]
