### PR TITLE
Fix paths in documentation comments

### LINKED ISSUE #810: Invalid references in generated Rust doc
To check locally: `cargo doc --document-private-items --no-deps`

will produce a list of warning:

<details>

```
warning: `[Runtime]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/node/mod.rs:34:67
   |
34 |     /// This method will be invoked in a blocking fashion by the [`Runtime`], therefore node
   |                                                                   ^^^^^^^^^ cannot be resolved, ignoring
   |
   = note: `#[warn(intra_doc_link_resolution_failure)]` on by default
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/mod.rs:50:26
   |
50 | /// An identifier for a [`Node`] that is opaque for type safety.
   |                          ^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[oak_runtime::Runtime]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/channel.rs:74:6
   |
74 | /// [`oak_runtime::Runtime`] [`oak_runtime::Runtime::channel_get_direction`].
   |      ^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[oak_runtime::Runtime::channel_get_direction]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/channel.rs:74:31
   |
74 | /// [`oak_runtime::Runtime`] [`oak_runtime::Runtime::channel_get_direction`].
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Runtime]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/channel.rs:82:42
   |
82 | /// be visible outside the internals of [`Runtime`].
   |                                          ^^^^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[oak_runtime::Runtime]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/channel.rs:279:10
    |
279 |     /// [`oak_runtime::Runtime`] to encode [`Channel`]s in messages.
    |          ^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:185:34
    |
185 |     /// Allow the corresponding [`Node`] to use the [`Handle`]s passed via the iterator.
    |                                  ^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:186:60
    |
186 |     /// This is achieved by adding the [`Handle`]s to the [`Node`]s [`HashMap`] of [`Handle`]s.
    |                                                            ^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[ChannelMapping::channels]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:275:58
    |
275 |     /// order to limit the scope of holding the lock on [`ChannelMapping::channels`].
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[ChannelMapping::channels]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:286:58
    |
286 |     /// order to limit the scope of holding the lock on [`ChannelMapping::channels`].
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Channel]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:387:24
    |
387 |     /// Creates a new [`Channel`] and returns a `(writer handle, reader handle)` pair.
    |                        ^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[ChannelReader]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:418:69
    |
418 |     /// - If all readers are in an erroneous status, e.g. when all [`ChannelReader`]s are orphaned,
    |                                                                     ^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Messages]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:654:10
    |
654 |     /// [`Messages`] which contain [`Handle`]'s.
    |          ^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:709:19
    |
709 |     /// Remove a [`Node`] by [`NodeId`] from the [`Runtime`].
    |                   ^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[crate::node::Configuration::new_instance]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:771:34
    |
771 |     /// itself and be passed to [`crate::node::Configuration::new_instance`] to be given to a new
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node::start]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:817:10
    |
817 |     /// [`Node::start`] on the instance, and finally storing a reference to the running instance
    |          ^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
```

</details>

### PR DESCRIPTION
**Pull request by rbehjati**
Fixes #810 

# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

File: sdk/rust/oak/src/grpc/mod.rs [hunk 1]
```diff
@@ -26,7 +26,9 @@ pub mod client;
 mod invocation;
 pub use invocation::Invocation;
 
-/// Result type that uses a [`proto::status::Status`] type for error values.
+/// Result type that uses a [`Status`] type for error values.
+///
+/// [`Status`]: oak_abi::proto::google::rpc
```
Comment (tiziano88) [inline sdk/rust/oak/src/grpc/mod.rs:31]: Should this be

```suggestion
/// [`Status`]: oak_abi::proto::google::rpc::Status
```

?

Comment (rbehjati) [reply sdk/rust/oak/src/grpc/mod.rs]: Yes! Thanks. Done.

**Comment by tiziano88** [comment]
FWIW, my suggestion is to go ahead and merge this PR as approved, and then create a separate one for the script to check for warnings.
