### PR TITLE
Fix oak functions integration test thread leak

### LINKED ISSUE #3891: Oak Functions tests leak threads
e.g. when running `cargo nextest run`:

```
        LEAK [ 170.113s] oak_functions_launcher::integration_test test_launcher_echo_virtual
        LEAK [  21.264s] oak_functions_launcher::integration_test test_launcher_key_value_lookup_virtual
```

In fact on my machine I can see:

```console
$ ps aux | grep qemu
tzn      1255413 98.8  0.2 504560 143372 ?       Sl   14:23  32:38 /usr/bin/qemu-system-x86_64 -enable-kvm -cpu IvyBridge-IBRS,enforce -m 256M -nodefaults -nographic -no-reboot -machine microvm,acpi=on -chardev socket,id=consock,fd=9 -serial chardev:consock -chardev socket,id=commsock,fd=11 -device virtio-serial-device,max_ports=1 -device virtconsole,chardev=commsock -device loader,file=/home/tzn/src/oak/oak_restricted_kernel_bin/target/x86_64-unknown-none/debug/oak_restricted_kernel_bin -bios /home/tzn/src/oak/stage0/target/x86_64-unknown-none/release/oak_stage0.bin
tzn      1255474 99.0  0.2 504560 143308 ?       Sl   14:23  32:41 /usr/bin/qemu-system-x86_64 -enable-kvm -cpu IvyBridge-IBRS,enforce -m 256M -nodefaults -nographic -no-reboot -machine microvm,acpi=on -chardev socket,id=consock,fd=9 -serial chardev:consock -chardev socket,id=commsock,fd=11 -device virtio-serial-device,max_ports=1 -device virtconsole,chardev=commsock -device loader,file=/home/tzn/src/oak/oak_restricted_kernel_bin/target/x86_64-unknown-none/debug/oak_restricted_kernel_bin -bios /home/tzn/src/oak/stage0/target/x86_64-unknown-none/release/oak_stage0.bin
tzn      1255477 98.7  0.3 503880 239052 ?       Sl   14:23  32:36 /usr/bin/qemu-system-x86_64 -enable-kvm -cpu IvyBridge-IBRS,enforce -m 256M -nodefaults -nographic -no-reboot -machine microvm,acpi=on -chardev socket,id=consock,fd=9 -serial chardev:consock -chardev socket,id=commsock,fd=11 -device virtio-serial-device,max_ports=1 -device virtconsole,chardev=commsock -device loader,file=/home/tzn/src/oak/oak_restricted_kernel_bin/target/x86_64-unknown-none/debug/oak_restricted_kernel_bin -bios /home/tzn/src/oak/stage0/target/x86_64-unknown-none/release/oak_stage0.bin
tzn      1275188  100  0.2 504560 143272 pts/8   Sl   14:31  25:36 /usr/bin/qemu-system-x86_64 -enable-kvm -cpu IvyBridge-IBRS,enforce -m 256M -nodefaults -nographic -no-reboot -machine microvm,acpi=on -chardev socket,id=consock,fd=9 -serial chardev:consock -chardev socket,id=commsock,fd=11 -device virtio-serial-device,max_ports=1 -device virtconsole,chardev=commsock -device loader,file=/home/tzn/src/oak/oak_restricted_kernel_bin/target/x86_64-unknown-none/debug/oak_restricted_kernel_bin -bios /home/tzn/src/oak/stage0/target/x86_64-unknown-none/release/oak_stage0.bin
tzn      1275235  100  0.2 504560 143384 pts/8   Sl   14:31  25:35 /usr/bin/qemu-system-x86_64 -enable-kvm -cpu IvyBridge-IBRS,enforce -m 256M -nodefaults -nographic -no-reboot -machine microvm,acpi=on -chardev socket,id=consock,fd=9 -serial chardev:consock -chardev socket,id=commsock,fd=11 -device virtio-serial-device,max_ports=1 -device virtconsole,chardev=commsock -device loader,file=/home/tzn/src/oak/oak_restricted_kernel_bin/target/x86_64-unknown-none/debug/oak_restricted_kernel_bin -bios /home/tzn/src/oak/stage0/target/x86_64-unknown-none/release/oak_stage0.bin
tzn      1275261  100  0.3 504560 239560 pts/8   Sl   14:31  25:35 /usr/bin/qemu-system-x86_64 -enable-kvm -cpu IvyBridge-IBRS,enforce -m 256M -nodefaults -nographic -no-reboot -machine microvm,acpi=on -chardev socket,id=consock,fd=9 -serial chardev:consock -chardev socket,id=commsock,fd=11 -device virtio-serial-device,max_ports=1 -device virtconsole,chardev=commsock -device loader,file=/home/tzn/src/oak/oak_restricted_kernel_bin/target/x86_64-unknown-none/debug/oak_restricted_kernel_bin -bios /home/tzn/src/oak/stage0/target/x86_64-unknown-none/release/oak_stage0.bin
tzn      1283140  0.0  0.0 222464  2632 pts/8    S+   14:56   0:00 grep qemu
```

even after the tests have finished (and I usually just run `killall qemu-system-x86_64` to clean it up).

We probably need to make sure that the qemu subprocess does not get leaked from the Oak Functions launcher

### PR DESCRIPTION
**Pull request by jul-sh**
Issue introduced in #3884, closes #3891.

### CODE REVIEW

**Review by conradgrobler — APPROVED** [review]
Thanks

**Comment by conradgrobler** [comment]
If this no longer output the nextest warnings about leaks, please also update the example logs in https://github.com/project-oak/oak/blob/main/docs/development.md with a new valid run.

File: oak_functions_launcher/tests/integration_test.rs [hunk 1]
```diff
@@ -113,6 +115,8 @@ async fn test_launcher_echo_virtual() {
 
     let response = client.invoke(b"xxxyyyzzz").await.expect("failed to invoke");
     assert_eq!(std::str::from_utf8(&response).unwrap(), "xxxyyyzzz");
+
+    background.kill();
```
Comment (tiziano88) [inline oak_functions_launcher/tests/integration_test.rs:119]: Could we have this happen on Drop, instead of explicitly having to call it?

**Comment by jul-sh** [comment]
> If this no longer output the nextest warnings about leaks, please also update the example logs in https://github.com/project-oak/oak/blob/main/docs/development.md with a new valid run.

done

File: oak_functions_launcher/tests/integration_test.rs (hunk 1 above)
Comment (jul-sh) [reply oak_functions_launcher/tests/integration_test.rs:119]: Nice idea. Curiously the function that returns this [claims that this already happens](https://github.com/project-oak/oak/blob/ef40f815281d4a3d6bc7959eb9797efa51d02e21/xtask/src/testing.rs#L39).

We cannot implement this on the existing type `Box<dyn Running>` since it conflicts with the existing Drop implementation of Box. We could however accomplish this by returning a type of our own, similar to `tokio::process::Command`. Might be worth doing so, but it'd be a slightly larger of xtask.

Comment (jul-sh) [reply oak_functions_launcher/tests/integration_test.rs]: Went with a small solution that adds an extra struct for background tasks that implements the dropping. Ideally I think _all_ tasks within xtask should be killed on drop. However implementing that may not be possible. The current solution will do for now.

**Review by tiziano88 — APPROVED** [review]
