### PR TITLE
Fix runtime tests

### LINKED ISSUE #1671: Fix runtime tests
The change in #1619 has caused the runtime tests to fail; although the tests do not actually fail!

This is because `node_stop` is now called when `proxy.stop` is called. Previously it was called before stopping the runtime:

https://github.com/rbehjati/oak/blob/caa91c86f4f2b9d451d7a8bae9b56d82375f4b3e/oak_runtime/src/tests.rs#L86-L100

### PR DESCRIPTION
**Pull request by daviddrysdale**
Fixes #1671 

# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [x] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by
        [Cloudbuild](/cloudbuild.yaml)
  - [ ] I have updated [documentation](/docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
(Second commit includes some explanation of why 2 tests are deleted in its commit message)

File: oak_runtime/src/tests.rs [hunk 1]
```diff
@@ -49,9 +50,18 @@ fn run_node_body(node_label: &Label, node_privilege: &NodePrivilege, node_body:
...
+        // Result of executing a `NodeBody` once complete (`None` before then).
+        value: Mutex<Option<Result<(), OakStatus>>>,
+        // Condition variable used to signal the completion of the test.
+        cv: Condvar,
+    };
+
     struct TestNode {
         node_body: Box<NodeBody>,
         node_privilege: NodePrivilege,
+        result: Arc<TestResult>,
```
Comment (tiziano88) [inline oak_runtime/src/tests.rs:64]: Have you considered a https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html ?

Comment (daviddrysdale) [reply oak_runtime/src/tests.rs:64]: A condition variable leapt to mind because this situation is exactly what they're designed for, but the Rust `Condvar` is kind of fiddly compared to some other implementations (e.g. Abseil's [`Mutex` with built-in condition var](https://abseil.io/docs/cpp/guides/synchronization#conditional-critical-sections)). 

`sync_channel` looks much cleaner (even though we don't need a lot of its function) so I'll give it a go.

Comment (daviddrysdale) [reply oak_runtime/src/tests.rs]: Yep, that works and makes the code much easier to follow than the naked `Condvar` version &ndash; thanks!

It also seems to have solved the problem with the previous version where a failed assertion in a test would result in the test hanging, but I don't yet understand why&hellip;

Comment (daviddrysdale) [reply oak_runtime/src/tests.rs]: (Answer: `mpsc:sender_receiver` detects if the sender has disconnected, including due to thread death, and emits a `RecvError` from the `receiver.recv()` call.)

**Comment by daviddrysdale** [comment]
@conradgrobler, please could you check in particular that the tests I've had to adjust or disable match your understanding of the current state of IFC enforcement?

File: oak_runtime/src/tests.rs [hunk 2]
```diff
@@ -440,80 +454,9 @@ fn create_node_invalid_configuration_err() {
...
-            );
-            assert_eq!(Err(OakStatus::ErrPermissionDenied), result);
-            Ok(())
-        }),
-    );
-}
-
-/// Create a test Node that creates a Node with a more confidential label and succeeds.
-#[test]
-fn create_node_more_confidential_label_ok() {
```
Comment (conradgrobler) [inline oak_runtime/src/tests.rs:482]: I think it could be possible to fix this test to cover a case we are not covering (although the name would probably need to change). The initial node can be changed to also have a public label, can be given the privilege to declassify tag_0 so that the channel creation can succeed.

I think a gRPC client node can be used to test creation of a non-public node, where the URI of the gRPC client configuration and the authority of the TLS endpoint tag line up. The gRPC client node will not try to connect to the external service until it receives an invocation, so it should be fine to use it without an actual service listening.

File: oak_runtime/src/tests.rs [hunk 3]
```diff
@@ -440,80 +454,9 @@ fn create_node_invalid_configuration_err() {
     );
 }
 
-/// Create a test Node that creates a Node with a less confidential label and fails.
-///
-/// If this succeeded, it would be a violation of information flow control, since the original
-/// confidential Node would be able to spawn "less confidential / public" Nodes and use their side
-/// effects as a covert channel to exfiltrate confidential data.
-#[test]
-fn create_node_less_confidential_label_err() {
```
Comment (conradgrobler) [inline oak_runtime/src/tests.rs:449]: I agree that we cannot test this at the moment because we can only create nodes from public nodes. It would be posible to test the same logic by tring to create a more trusted node from a public untrusted node (although I know that we don't have full support for integrity labels yet I think there is enough to actually test this logic).

**Review by conradgrobler — APPROVED** [review]
I think there are some cases we are not currently covering and the removed tests could be changed to cover some of these. But this should perhaps be a separate PR that could include some of the other missing cases as well.

File: oak_runtime/src/tests.rs (hunk 3 above)
Comment (daviddrysdale) [reply oak_runtime/src/tests.rs:449]: I had a go, but unfortunately it's not straightforward &ndash; the tests currently use a logging pseudo-Node as the object to be created, but that can only be created with a `public_untrusted` label anyway (since #1688).  Other types of Node also fail to be (easily) created from a test:
 - Wasm Nodes fail to be created because there isn't a Wasm module available
 - gRPC pseudo-Nodes fail to be created because there isn't gRPC config available

So I agree it should be possible to put something in to replace this test, but it's a bit more involved than this PR.

File: oak_runtime/src/tests.rs (hunk 1 above)
Comment (tiziano88) [reply oak_runtime/src/tests.rs]: yeah that was my mental process too: "nice, I guess CondVar is meant for exactly this case it seems... if only there was something that keeps a condvar together with the inner value.. I guess that would be a sort of channel... and it may also detect when the sender disappears without sending anything" :)

File: oak_runtime/src/tests.rs (hunk 3 above)
Comment (conradgrobler) [reply oak_runtime/src/tests.rs:449]: Yes, I thought that it would fall back on the default root TLS certs, but I forgot that they are in the loader, not the runtime.

**Review by rbehjati — APPROVED** [review]
Very nice. Thanks.

File: oak_runtime/src/tests.rs (hunk 3 above)
Comment (daviddrysdale) [reply oak_runtime/src/tests.rs:449]: I've added another commit reinstating a couple of variant tests, but I'm not completely happy with the `include_bytes!("../../examples/certs/local/local.pem")` stuff &ndash; WDYT?

Comment (conradgrobler) [reply oak_runtime/src/tests.rs:449]: I think using `include_str! in the tests is fine.

The other option I thought about was to create a dummy node type specifically for testing that can be created with empty configuration (something that we can safely mark as sandboxed because it doesn't ever to anything other than close the initial handle it receives and therefore does not have the restrictions on privilege). This feels a bit messy, seeing that it will be visible to developers as a possible node configuration but will probably only ever be useful in the runtime internally for testing.

On balance, I prefer the option you currently implemented.

**Review by conradgrobler — APPROVED** [review]
LGTM
