### PR TITLE
Enlighten fw_cfg to support AMD SEV-SNP

### LINKED ISSUE #3636: Implement AMD SEV-SNP enlightenment for  the QEMU fw_cfg DMA feature
The current implementation of the DMA support for the fw_cfg device will not work on AMD SEV-SNP, as it assumes that the hypervisor can write to the guest memory. We need to implement a bounce buffer in shared memory and copy the data over into the actual location.

To avoid having to share a large amount of memory we should probably share a single 4KiB page with the hypervisor and read the content 4KiB at a time.

### PR DESCRIPTION
**Pull request by conradgrobler**
The memory-encryption part is currently untested as we cannot run Linux workloads with initial RAM disks on AMD SEV-SNP yet using the stage 0 firmware.

Fixes #3636

### CODE REVIEW

File: stage0/src/fw_cfg.rs [hunk 1]
```diff
@@ -27,6 +30,23 @@ const FWCFG_PORT_DMA: u16 = 0x514;
...
+/// A single 4KiB buffer that is 4KiB page-aligned.
+#[repr(C, align(4096))]
+#[derive(Debug)]
+pub struct DmaBuffer {
+    data: [u8; Size4KiB::SIZE as usize],
+}
+
+static_assertions::assert_eq_size!(DmaBuffer, [u8; Size4KiB::SIZE as usize]);
+
+impl DmaBuffer {
```
Comment (andrisaar) [inline stage0/src/fw_cfg.rs:42]: How about implementing Default for this struct?

File: stage0/src/sev.rs [hunk 2]
```diff
@@ -96,18 +84,44 @@ pub fn init_ghcb(
 
 pub fn deinit_ghcb(snp: bool, encrypted: u64) {
     let ghcb_addr = GHCB_WRAPPER.get().unwrap().lock().get_gpa().as_u64();
+    unshare_page(PhysAddr::new(ghcb_addr), snp, encrypted);
+}
 
+/// Shares a single 4KiB page containing the address with the hypervisor.
+pub fn share_page(address: PhysAddr, snp: bool, encrypted: u64) {
```
Comment (andrisaar) [inline stage0/src/sev.rs:91]: These functions should probably take a `Page<Size4KiB>` as an argument instead of a raw PhysAddr, but I'm fine delegating that clean-up to some later point in time.

**Review by andrisaar — APPROVED** [review]

File: stage0/src/fw_cfg.rs (hunk 1 above)
Comment (conradgrobler) [reply stage0/src/fw_cfg.rs:42]: Done.

File: stage0/src/sev.rs (hunk 2 above)
Comment (conradgrobler) [reply stage0/src/sev.rs:91]: Good point. Done, at least an initial pass at making it a bit better.

**Review by conradgrobler — COMMENTED** [review]
Thanks.
