### PR TITLE
Return ChannelReadStatus from Receiver::wait

### LINKED ISSUE #1078: Return channel read status from `Receiver::wait`
Currently `Receiver::wait` only returns `ErrBadHandle` as overall status if the (only) channel that is being waited on resulted in any error. There seems to be no way for a `Receiver` user to figure out why the wait actually failed, in that case.

https://github.com/project-oak/oak/blob/474e890121fe00211cdfb4e3445100697a64a47b/sdk/rust/oak/src/io/receiver.rs#L68-L78

@rbehjati since you are most familiar with this logic, could you look into it?

### PR DESCRIPTION
**Pull request by rbehjati**
Fixes #1078 

# Checklist

- [x] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by
        [Cloudbuild](/cloudbuild.yaml)
  - [ ] I have updated [documentation](/docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

File: sdk/rust/oak/src/lib.rs [hunk 1]
```diff
@@ -505,7 +505,7 @@ pub fn run_event_loop<T: crate::io::Decodable, N: Node<T>>(
                         );
                         return;
                     }
-                    ErrBadHandle | ErrChannelClosed | ErrPermissionDenied => {
+                    ErrBadHandle | ErrChannelClosed | ErrPermissionDenied | ErrInternal => {
```
Comment (rbehjati) [inline sdk/rust/oak/src/lib.rs:508]: @tiziano88 I don't think any of these error statuses (apart from ErrInternal) will be returned any more. Should I still keep them here for completeness?

File: oak/server/rust/oak_runtime/src/runtime/mod.rs [hunk 2]
```diff
@@ -596,19 +596,17 @@ impl Runtime {
     }
 
     // TODO(#970): Improve the documentation.
```
Comment (rbehjati) [inline oak/server/rust/oak_runtime/src/runtime/mod.rs:598]: @tiziano88 If the modified documentation is good enough, I can remove this line and close #970. WDYT?

File: sdk/rust/oak/src/lib.rs [hunk 3]
```diff
@@ -519,9 +519,17 @@ pub fn run_event_loop<T: crate::io::Decodable, N: Node<T>>(
                     }
                 }
             }
-            Ok(()) => {
-                trace!("{:?}: wait over", in_channel);
-            }
+            Ok(status) => match status {
+                ChannelReadStatus::ReadReady => trace!("{:?}: wait over", in_channel),
+                _ => {
```
Comment (rbehjati) [inline sdk/rust/oak/src/lib.rs:524]: If the status is `InvalidChannel`, `Orphaned`, or `PermissionDenied` we reach this arm. I suppose in all these cases we want to return immediately (the status will never be `NotReady` IIUC).

Comment (tiziano88) [reply sdk/rust/oak/src/lib.rs:524]: Could you enumerate them explicitly in this arm? So if we ever add a new status, we will be forced to reconsider this match statement. Also, based on your comment, it sounds like we want to log an `error` in the `NotReady` case, since I guess it would mean there is a logic error somewhere, right?

File: sdk/rust/oak/src/io/receiver.rs [hunk 4]
```diff
@@ -66,14 +66,30 @@ impl<T: Decodable> Receiver<T> {
...
         // TODO(#500): Consider creating the handle notification space once and for all in `new`.
         let read_handles = vec![self.handle];
         let mut space = crate::new_handle_space(&read_handles);
         crate::prep_handle_space(&mut space);
         let status =
             unsafe { oak_abi::wait_on_channels(space.as_mut_ptr(), read_handles.len() as u32) };
-        crate::result_from_status(status as i32, ())
+
+        match space
+            .get(oak_abi::SPACE_BYTES_PER_HANDLE - 1)
```
Comment (tiziano88) [inline sdk/rust/oak/src/io/receiver.rs:84]: Trying to get the byte by addressing it from the end seems harder to follow and more fragile in case the layout changes (assuming it's more likely we will add things to the end of this representation). In fact I think perhaps we should consider a proper struct (perhaps tagged with `repr(c)`) to make sure that `new_handle_space` and this logic are in sync and binary-compatible (also ideally with the Runtime side of things, but I'm not sure that's feasible. Or we should just bite the bullet and separate inputs and outputs as per https://github.com/project-oak/oak/issues/918. WDYT? cc @daviddrysdale

File: sdk/rust/oak/src/io/receiver.rs [hunk 5]
```diff
@@ -66,14 +66,30 @@ impl<T: Decodable> Receiver<T> {
...
+            .cloned()
+            .map(i32::from)
+            .and_then(ChannelReadStatus::from_i32)
+        {
+            Some(channel_status) => Ok(channel_status),
+            None => {
+                crate::result_from_status(status as i32, ()).map(|_| Err(OakStatus::ErrInternal))?
```
Comment (tiziano88) [inline sdk/rust/oak/src/io/receiver.rs:91]: Log the error before discarding?

File: sdk/rust/oak/src/lib.rs (hunk 1 above)
Comment (tiziano88) [reply sdk/rust/oak/src/lib.rs:508]: If they should not happen, please capture them explicitly and log an error. If you had such insight to prompt you to write it down in this comment, why disregard this valuable information in the code? It would also make the code self-explanatory.

File: oak/server/rust/oak_runtime/src/runtime/mod.rs [hunk 6]
```diff
@@ -596,19 +596,17 @@ impl Runtime {
...
-    /// Waits on a slice of `ChannelHalf`s, blocking until one of the following conditions:
+    /// Waits on a slice of `ChannelHalf`s, until at least one of the channels is able to read a
+    /// message, provided that all of the channels are valid; otherwise returns immediately.
```
Comment (tiziano88) [inline oak/server/rust/oak_runtime/src/runtime/mod.rs:600]: IIUC it will stop waiting if a channel becomes orphan, which means that "waits until at least one of the channels is able to read a message" is not always true.

File: sdk/rust/oak/src/io/receiver.rs [hunk 7]
```diff
@@ -66,14 +66,30 @@ impl<T: Decodable> Receiver<T> {
     }
 
     /// Wait for a value to be available from this receiver.
+    ///
+    /// May return the following error statuses:
+    /// - `Err(OakStatus::ErrTerminated)`: if the Oak Runtime is terminating.
+    /// - `Err(OakStatus::ErrInternal)`: if cannot extract the `ChannelReadStatus` form the buffer
```
Comment (conradgrobler) [inline sdk/rust/oak/src/io/receiver.rs:72]: s/form/from/?

File: sdk/rust/oak/src/io/receiver.rs [hunk 8]
```diff
@@ -66,14 +66,29 @@ impl<T: Decodable> Receiver<T> {
...
+        match crate::result_from_status(status as i32, ()) {
+            Err(OakStatus::ErrTerminated) => Err(OakStatus::ErrTerminated),
+            _ => match space
+                .get(oak_abi::SPACE_BYTES_PER_HANDLE - 1)
+                .cloned()
+                .map(i32::from)
+                .and_then(ChannelReadStatus::from_i32)
+            {
+                Some(channel_status) => Ok(channel_status),
+                None => unreachable!("wait_on_channels always yields a valid channel read status if the returned status is not Err(OakStatus::ErrTerminated)."),
```
Comment (tiziano88) [inline sdk/rust/oak/src/io/receiver.rs:90]: Reading the documentation of `unreachable`, it feels like it is meant for much more self-contained impossible conditions (e.g. truly unreachable match arms, code after a loop that never terminates, etc): https://doc.rust-lang.org/std/macro.unreachable.html

I don't think it should be used for this kind of precondition checks, for which panic seems the default choice.

Alternatively we may decide to log at `error` level, since that's reserved for logic errors. I guess it is worth having a quick discussion on panic vs error on a GitHub issue, could you start one? For now, feel free to use what you prefer, it should be easy to later on grep for `error!` or `panic!` and make sure they are consistent, hopefully.

File: sdk/rust/oak/src/io/receiver.rs [hunk 9]
```diff
@@ -66,14 +66,29 @@ impl<T: Decodable> Receiver<T> {
...
         let read_handles = vec![self.handle];
         let mut space = crate::new_handle_space(&read_handles);
         crate::prep_handle_space(&mut space);
         let status =
             unsafe { oak_abi::wait_on_channels(space.as_mut_ptr(), read_handles.len() as u32) };
-        crate::result_from_status(status as i32, ())
+
+        match crate::result_from_status(status as i32, ()) {
+            Err(OakStatus::ErrTerminated) => Err(OakStatus::ErrTerminated),
+            _ => match space
```
Comment (tiziano88) [inline sdk/rust/oak/src/io/receiver.rs:83]: Shouldn't this pass through also `ErrInvalidArgs` and others? Either way, could you explain why some values are matched and some ignored in a comment, for future reference?

File: sdk/rust/oak/src/io/receiver.rs [hunk 10]
```diff
@@ -66,14 +66,29 @@ impl<T: Decodable> Receiver<T> {
...
+                .get(oak_abi::SPACE_BYTES_PER_HANDLE - 1)
+                .cloned()
+                .map(i32::from)
+                .and_then(ChannelReadStatus::from_i32)
+            {
```
Comment (tiziano88) [inline sdk/rust/oak/src/io/receiver.rs:88]: How about

```rust
..
.and_then(ChannelReadStatus::from_i32)
.ok_or_else(|| unreachable!(...))
```

File: oak/server/rust/oak_runtime/src/node/wasm/mod.rs [hunk 11]
```diff
@@ -421,6 +421,14 @@ impl WasmInterface {
     }
 
     /// Corresponds to the host ABI function [`wait_on_channels`](https://github.com/project-oak/oak/blob/master/docs/abi.md#wait_on_channels).
+    ///
+    /// May return the following error statuses:
+    /// - `Err(OakStatus::ErrTerminated)`: if [`Runtime`] is terminating. In this cases, read
```
Comment (tiziano88) [inline oak/server/rust/oak_runtime/src/node/wasm/mod.rs:426]:
```suggestion
    /// - `Err(OakStatus::ErrTerminated)`: if [`Runtime`] is terminating. In this case, read
```

File: oak/server/rust/oak_runtime/src/node/wasm/mod.rs [hunk 12]
```diff
@@ -421,6 +421,14 @@ impl WasmInterface {
...
+    ///   statuses in `status_buff` do not reflect the actual read statuses.
+    /// - `Err(OakStatus::ErrInvalidArgs)`: if cannot parse `status_buff` into channel handles.
+    /// - `Err(OakStatus::ErrBadHandle)`: if all channels have erroneous statuses.
```
Comment (tiziano88) [inline oak/server/rust/oak_runtime/src/node/wasm/mod.rs:429]: Just to double check (I know, I should know by now :P ): if there are 10 channels, and 9 of them are invalid and 1 ready, it returns Ok, but if all of them are invalid then it returns ErrBadHandle?

File: oak/server/rust/oak_runtime/src/runtime/mod.rs (hunk 2 above)
Comment (tiziano88) [reply oak/server/rust/oak_runtime/src/runtime/mod.rs:598]: SG, but would it make sense to actually update https://github.com/project-oak/oak/blob/master/docs/abi.md#wait_on_channels and redirect both this documentation and that on the wasm node implementation to that? Otherwise we still have 3 pieces of text saying essentially the same thing in slightly different ways.

File: oak/server/rust/oak_runtime/src/node/wasm/mod.rs (hunk 12 above)
Comment (rbehjati) [reply oak/server/rust/oak_runtime/src/node/wasm/mod.rs]: That is true, and it sounds counterintuitive! IIRC the reason for adding the check for all invalid channels and then returning `Err(OakStatus::ErrBadHandle)` was to have an extra flag to let the caller functions more quickly detect the situation. But the caller functions may as well check the situation themselves.
That check can be removed as I have done in this [PR](https://github.com/project-oak/oak/pull/1123).

**Comment by tiziano88** [comment]
BTW, would it help to add `must_use` somewhere? https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

**Comment by rbehjati** [comment]
> BTW, would it help to add `must_use` somewhere? https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

Like where? Does not `clippy` already check these things? Or maybe I don't completely understand your comment.

File: sdk/rust/oak/src/io/receiver.rs [hunk 13]
```diff
@@ -66,14 +66,33 @@ impl<T: Decodable> Receiver<T> {
...
         crate::prep_handle_space(&mut space);
         let status =
             unsafe { oak_abi::wait_on_channels(space.as_mut_ptr(), read_handles.len() as u32) };
-        crate::result_from_status(status as i32, ())
+
+        match crate::result_from_status(status as i32, ()) {
+            Err(OakStatus::ErrTerminated) => Err(OakStatus::ErrTerminated),
+            Err(OakStatus::ErrInvalidArgs) => panic!("Indicates that `space` is corrupted. This should never happen."),
+            // The only other output from `oak_abi::wait_on_channels` is `OakStatus::Ok`, 
+            // which is handled below. Other `OakStatus` error codes never happen.
```
Comment (tiziano88) [inline sdk/rust/oak/src/io/receiver.rs:85]: Is it possible to add the logic that shows this is actually the case?

```rust
Err(_) => panic!("should never happen")
Ok(...) => space...
```

**Comment by tiziano88** [comment]
> > BTW, would it help to add `must_use` somewhere? https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute
> 
> Like where? Does not `clippy` already check these things? Or maybe I don't completely understand your comment.

I meant like tagging ChannelReadStatus with `must_use`, so that if we forget to use it, clippy will complain.

File: sdk/rust/oak/src/io/receiver.rs (hunk 13 above)
Comment (rbehjati) [reply sdk/rust/oak/src/io/receiver.rs]: I tried that, but `clippy` does not like it:
```
error: `Err(_)` matches all errors
  --> sdk/rust/oak/src/io/receiver.rs:84:13
   |
84 |             Err(_) => panic!("Other errors never happen."),
   |             ^^^^^^
   |
   = note: `-D clippy::match-wild-err-arm` implied by `-D warnings`
   = note: match each error separately or use the error output
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_wild_err_arm
```
I can still add a separate arm for the `Ok` case.

Comment (tiziano88) [reply sdk/rust/oak/src/io/receiver.rs]: Yeah that's even better!

**Comment by rbehjati** [comment]
> I meant like tagging ChannelReadStatus with `must_use`, so that if we forget to use it, clippy will complain.

Interesting. I can look into that.
