### PR TITLE
Retry sending requests in HTTP tests to make the tests stable

### LINKED ISSUE #1462: HTTP node tests are flaky
> Uhmm this seems to make the HTTP node tests fail sometimes, but not consistently. Not sure why, will look into it. @rbehjati let me know if you have any suggestions on why that may be happening

so actually I tried again from `main`, and it seems that tests are flaky there too. To reproduce:

```bash
export RUST_LOG=debug
cd oak_runtime
cargo test --package oak_runtime --lib -- node --nocapture
```

and then rerun the `cargo test` a few times. I got a failure roughtly 1 out of 5 times.

<details><summary>logs</summary>
<p>

```
    Finished test [unoptimized + debuginfo] target(s) in 0.10s
     Running target/debug/deps/oak_runtime-f41ce2eeb10d11e5

running 19 tests
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http::tests] Create runtime for test
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 10859620126471780718 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 14154969170481411718 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 6028826501016594447 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 16096544177349775597 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((10859620126471780718, 14154969170481411718))
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 16698263373585990938 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 9092960943208256323 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 244963718117020840 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((16096544177349775597, 9092960943208256323))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((16698263373585990938, 244963718117020840))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 2638176703059791071 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 15754702411688475858 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 16409535109310484427 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((6028826501016594447, 15754702411688475858))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 11927899315350453922 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 9360967439716317465 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((2638176703059791071, 16409535109310484427))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 11888636142326083607 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_other_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] entrypoint 'oak_main' export not found
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] could not validate entrypoint: ErrInvalidArgs
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((11927899315350453922, 11888636142326083607))
[2020-09-10T20:47:15Z WARN  oak_runtime] could not create node: IncorrectWebAssemblyModuleName
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 10552541542430126522 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 1
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Err(ErrInvalidArgs)
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 12335443945007934671 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 15583588925823706518 maps to Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 2196097866962909478 maps to Channel 1 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((10552541542430126522, 12335443945007934671))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 1767916906041923217 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 1
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 3120311075007141291 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((15583588925823706518, 2196097866962909478))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 1291357445641949921 maps to Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 9571224628934017081 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 1
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(11927899315350453922, Message { bytes: [10, 9, 9, 150, 229, 110, 9, 144, 7, 68, 216], handles: [15583588925823706518] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(15754702411688475858)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((3120311075007141291, 9571224628934017081))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 3555956587273005122 maps to Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(11927899315350453922, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(15754702411688475858) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 6330247248751785548 maps to Channel 1 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(11927899315350453922)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 14923236747254485945 maps to Channel 1 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((3555956587273005122, 14923236747254485945))
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 6028826501016594447 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(2638176703059791071, Message { bytes: [10, 9, 9, 66, 40, 30, 5, 173, 75, 89, 49], handles: [3555956587273005122] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 6028826501016594447 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((1291357445641949921, 6330247248751785548))
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(2638176703059791071, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(11927899315350453922) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(10552541542430126522, Message { bytes: [10, 9, 9, 225, 82, 139, 65, 193, 210, 235, 17], handles: [1291357445641949921] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(2638176703059791071)
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(10552541542430126522, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(2638176703059791071) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(10552541542430126522)
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
test node::wasm::tests::wasm_starting_module_without_content_fails ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(10552541542430126522) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 580815582432483639 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((1767916906041923217, 580815582432483639))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): wait_on_channels: channels not ready, parking thread Thread { id: ThreadId(16), name: None }
[2020-09-10T20:47:15Z DEBUG rustls::anchors] add_pem_file processed 1 valid and 0 invalid certs
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 9155368652591746135 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG rustls::anchors] add_pem_file processed 1 valid and 0 invalid certs
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] test-node: Waiting for invocation channel
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1)
[2020-09-10T20:47:15Z DEBUG rustls::anchors] add_pem_file processed 1 valid and 0 invalid certs
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): wait_on_channels: channels not ready, parking thread Thread { id: ThreadId(19), name: None }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1) -> Ok([ReadReady])
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(12335443945007934671)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((9360967439716317465, 9155368652591746135))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 11080559098524874464 maps to Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::dns] resolving host="localhost"
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(12335443945007934671) -> Ok(Some(Message { bytes: [10, 9, 9, 225, 82, 139, 65, 193, 210, 235, 17], handles: [11080559098524874464] }))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(12335443945007934671)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(12335443945007934671) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] test-node: Starting HTTP server pseudo-Node on: [::]:2527
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connecting to [::1]:2527
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::dns] resolving host="localhost"
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::dns] resolving host="localhost"
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connected to [::1]:2527
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] ThreadId(18): Started HTTP server pseudo-node on port 2527
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] No cached session for DNSNameRef("localhost")
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] Not resuming any session
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::http] Received incoming TLS stream: TcpStream { addr: V6([::1]:2527), peer: V6([::1]:33922), fd: 21 }
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connecting to [::1]:2525
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] test-node: Waiting for invocation channel
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:2525
thread 'node::http::tests::test_https_server_can_serve_https_requests' panicked at 'assertion failed: resp.is_ok()', src/node/http/tests.rs:91[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1) -> Ok([ReadReady])
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(11888636142326083607)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 15642419903814064830 maps to Channel 1 WRITE
:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test node::http::tests::test_https_server_can_serve_https_requests ... FAILED
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(11888636142326083607) -> Ok(Some(Message { bytes: [10, 9, 9, 150, 229, 110, 9, 144, 7, 68, 216], handles: [15642419903814064830] }))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(11888636142326083607)
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] test-node: Waiting for invocation channel
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }, Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [2, 2, 2] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(11888636142326083607) -> Ok(())
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connecting to [::1]:2526
[2020-09-10T20:47:15Z WARN  oak_runtime] NodeId(1): cannot write to Label { confidentiality_tags: [], integrity_tags: [] }
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] test-node: Starting HTTP server pseudo-Node on: [::]:2526
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:2526
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }, Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [2, 2, 2] })) }], integrity_tags: [] }) -> Err(ErrPermissionDenied)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: []
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connected to 127.0.0.1:2526
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] ThreadId(14): Started HTTP server pseudo-node on port 2526
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
test tests::create_channel_with_more_confidential_label_from_non_public_node_with_privilege_err ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::http] Received incoming TLS stream: TcpStream { addr: V6([::ffff:127.0.0.1]:2526), peer: V6([::ffff:127.0.0.1]:33940), fd: 22 }
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 11705927381946070715 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 490605741076439707 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 5932870466176810717 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 13595452974177765549 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG rustls::server::hs] decided upon suite SupportedCipherSuite { suite: TLS13_CHACHA20_POLY1305_SHA256, kx: BulkOnly, bulk: CHACHA20_POLY1305, hash: SHA256, sign: None, enc_key_len: 32, fixed_iv_len: 12, explicit_nonce_len: 0 }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((11705927381946070715, 13595452974177765549))
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] flushed 57 bytes
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((490605741076439707, 5932870466176810717))
[2020-09-10T20:47:15Z ERROR oak_runtime::node::http] Client-connection error: Custom { kind: InvalidData, error: CorruptMessage }
[2020-09-10T20:47:15Z ERROR oak_runtime::node::http] Error when processing TLS stream: Custom { kind: Other, error: "TLS Error: Custom { kind: InvalidData, error: CorruptMessage }" }
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1) -> Ok([ReadReady])
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(16409535109310484427)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] read 0 bytes
[2020-09-10T20:47:15Z ERROR oak_runtime] Wasm module signature verification failed for oak_module: ring::error::Unspecified
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 10709409905608189541 maps to Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::conn] parse error (connection closed before message completed) with 0 bytes
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::dispatch] read_head error: connection closed before message completed
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(16409535109310484427) -> Ok(Some(Message { bytes: [10, 9, 9, 66, 40, 30, 5, 173, 75, 89, 49], handles: [10709409905608189541] }))
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 13595452974177765549 => Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 11705927381946070715 => Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(16409535109310484427)
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG hyper::server::shutdown] signal received, starting graceful shutdown
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(16409535109310484427) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] HTTP server pseudo-node terminated with Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] test-node: Starting HTTP server pseudo-Node on: [::]:2525
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::wasm::tests::wasm_verify_module_signature_fails ... [2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
ok[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 15583588925823706518 => Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 2196097866962909478 => Channel 1 READ
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] ThreadId(15): Started HTTP server pseudo-node on port 2525
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 15642419903814064830 => Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG hyper::server::shutdown] signal received, starting graceful shutdown
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] HTTP server pseudo-node terminated with Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 15583588925823706518 => Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 2196097866962909478 => Channel 1 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): new ABI handle 8188998132612729810 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 15642419903814064830 => Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): new ABI handle 5748044951194180441 maps to Channel 0 READ

[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }) -> Ok((8188998132612729810, 5748044951194180441))
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 1 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_write(8188998132612729810, Message { bytes: [14, 12, 88], handles: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=1, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_write(8188998132612729810, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_read(5748044951194180441)
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=1, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): cannot read from Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_read(5748044951194180441) -> Err(ErrPermissionDenied)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: [8188998132612729810, 5748044951194180441]
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
test node::http::tests::test_https_server_cannot_serve_http_requests ... ok
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
test tests::create_channel_with_more_confidential_label_from_public_untrusted_node_ok ... ok
[2020-09-10T20:47:15Z DEBUG rustls::client::tls13] Not resuming
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
[2020-09-10T20:47:15Z DEBUG rustls::client::tls13] TLS1.3 encrypted extensions: [ServerNameAck]
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] ALPN protocol is None
[2020-09-10T20:47:15Z WARN  rustls::session] Sending fatal alert BadCertificate
[2020-09-10T20:47:15Z ERROR oak_runtime::node::http] Client-connection error: Custom { kind: UnexpectedEof, error: "tls handshake eof" }
[2020-09-10T20:47:15Z ERROR oak_runtime::node::http] Error when processing TLS stream: Custom { kind: Other, error: "TLS Error: Custom { kind: UnexpectedEof, error: \"tls handshake eof\" }" }
[2020-09-10T20:47:15Z DEBUG rustls::anchors] add_pem_file processed 1 valid and 0 invalid certs
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::dns] resolving host="localhost"
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connecting to [::1]:2527
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::http] Received incoming TLS stream: TcpStream { addr: V6([::1]:2527), peer: V6([::1]:33932), fd: 5 }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG hyper::client::connect::http] connected to [::1]:2527
[2020-09-10T20:47:15Z WARN  oak_runtime] NodeId(1): cannot write to Label { confidentiality_tags: [], integrity_tags: [] }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }) -> Err(ErrPermissionDenied)
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] No cached session for DNSNameRef("localhost")
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] Not resuming any session
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: []
[2020-09-10T20:47:15Z WARN  oak_runtime] NodeId(1): cannot write to Label { confidentiality_tags: [], integrity_tags: [] }
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }) -> Err(ErrPermissionDenied)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: []
test tests::create_node_more_confidential_label_ok ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
test tests::create_node_invalid_configuration_err ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 0
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): new ABI handle 1052340951842084367 maps to Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): new ABI handle 279083569327136254 maps to Channel 0 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }) -> Ok((1052340951842084367, 279083569327136254))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_write(1052340951842084367, Message { bytes: [14, 12, 88], handles: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_write(1052340951842084367, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_read(279083569327136254)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_read(279083569327136254) -> Ok(Some(Message { bytes: [14, 12, 88], handles: [] }))
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: [279083569327136254, 1052340951842084367]
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG rustls::server::hs] decided upon suite SupportedCipherSuite { suite: TLS13_CHACHA20_POLY1305_SHA256, kx: BulkOnly, bulk: CHACHA20_POLY1305, hash: SHA256, sign: None, enc_key_len: 32, fixed_iv_len: 12, explicit_nonce_len: 0 }
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z WARN  oak_runtime] NodeId(1): cannot write to Label { confidentiality_tags: [], integrity_tags: [] }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }) -> Err(ErrPermissionDenied)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: []
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
test tests::create_channel_with_more_confidential_label_from_public_node_with_privilege_ok ... ok
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
test tests::create_node_less_confidential_label_err ... ok
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create runtime for test
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Create test Node
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Start test Node instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] })
[2020-09-10T20:47:15Z WARN  oak_runtime] NodeId(1): cannot write to Label { confidentiality_tags: [], integrity_tags: [] }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(1): channel_create(Label { confidentiality_tags: [Tag { tag: Some(GrpcTag(GrpcTag { authorization_bearer_token_hmac: [1, 1, 1] })) }], integrity_tags: [] }) -> Err(ErrPermissionDenied)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: []
[2020-09-10T20:47:15Z DEBUG rustls::client::tls13] Not resuming
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node TestNode(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime::tests] Stop runtime..done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
test tests::create_node_same_label_ok ... ok
[2020-09-10T20:47:15Z DEBUG rustls::client::tls13] TLS1.3 encrypted extensions: [ServerNameAck]
[2020-09-10T20:47:15Z DEBUG rustls::client::hs] ALPN protocol is None
[2020-09-10T20:47:15Z DEBUG rustls::client::tls13] Ticket saved
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] flushed 57 bytes
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] read 57 bytes
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] parsed 2 headers
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::conn] incoming body is empty
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] Handling HTTP request; request size: 0 bytes, label: Label { confidentiality_tags: [], integrity_tags: [] }
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::http] Inject the request into the Oak Node
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 2
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 9961052006950199576 maps to Channel 2 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 1791300487480186213 maps to Channel 2 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((9961052006950199576, 1791300487480186213))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] create new Channel object with ID 3
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 14881253896451425314 maps to Channel 3 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 3680328595663417379 maps to Channel 3 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_create(Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok((14881253896451425314, 3680328595663417379))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(9961052006950199576, Message { bytes: [10, 1, 47, 18, 3, 103, 101, 116, 34, 15, 10, 13, 111, 97, 107, 45, 108, 97, 98, 101, 108, 45, 98, 105, 110, 34, 22, 10, 4, 104, 111, 115, 116, 18, 14, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 50, 53, 50, 55], handles: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(9961052006950199576, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(11080559098524874464, Message { bytes: [10, 9, 9, 101, 149, 61, 122, 77, 250, 219, 24, 18, 9, 9, 34, 132, 98, 22, 147, 213, 132, 206], handles: [1791300487480186213, 14881253896451425314] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(11080559098524874464, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): wait_on_channels: thread Thread { id: ThreadId(19), name: None } re-woken
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9961052006950199576)
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 2 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9961052006950199576) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(1791300487480186213)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1) -> Ok([ReadReady])
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(6330247248751785548)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(1791300487480186213) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(14881253896451425314)
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 7424337281389512419 maps to Channel 2 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(0): new ABI handle 12021382004607466382 maps to Channel 3 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(6330247248751785548) -> Ok(Some(Message { bytes: [10, 9, 9, 101, 149, 61, 122, 77, 250, 219, 24, 18, 9, 9, 34, 132, 98, 22, 147, 213, 132, 206], handles: [7424337281389512419, 12021382004607466382] }))
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(12021382004607466382, Message { bytes: [16, 200, 1], handles: [] })
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_write(12021382004607466382, ...) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(14881253896451425314) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] Generating response for runtime 0 and reader 3680328595663417379.
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): wait_on_channels(count=1) -> Ok([ReadReady])
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(3680328595663417379)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_read(3680328595663417379) -> Ok(Some(Message { bytes: [16, 200, 1], handles: [] }))
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] flushed 75 bytes
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] read 75 bytes
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::io] parsed 2 headers
[2020-09-10T20:47:15Z DEBUG hyper::proto::h1::conn] incoming body is empty
[2020-09-10T20:47:15Z DEBUG hyper::client::pool] pooling idle connection for ("https", localhost:2527)
[2020-09-10T20:47:15Z DEBUG hyper::server::shutdown] signal received, starting graceful shutdown
[2020-09-10T20:47:15Z DEBUG rustls::session] Sending warning alert CloseNotify
[2020-09-10T20:47:15Z INFO  oak_runtime::node::http] HTTP server pseudo-node terminated with Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 7424337281389512419 => Channel 2 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 12021382004607466382 => Channel 3 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 3680328595663417379 => Channel 3 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 1291357445641949921 => Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 6330247248751785548 => Channel 1 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 11080559098524874464 => Channel 1 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 7424337281389512419 => Channel 2 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 12021382004607466382 => Channel 3 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 3680328595663417379 => Channel 3 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 1291357445641949921 => Channel 1 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 6330247248751785548 => Channel 1 READ
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 11080559098524874464 => Channel 1 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=2, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=2, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 3 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=3, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=3, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 1 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=1, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=1, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::http::tests::test_https_server_does_not_terminate_after_a_bad_request ... ok
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] entrypoint 'oak_main' export has incorrect function signature: Signature { params: [], return_type: None }
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] could not validate entrypoint: ErrInvalidArgs
[2020-09-10T20:47:15Z WARN  oak_runtime] could not create node: IncorrectWebAssemblyModuleName
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Err(ErrInvalidArgs)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9571224628934017081)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9571224628934017081) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 3120311075007141291 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 3120311075007141291 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::wasm::tests::wasm_starting_module_with_wrong_signature_2_fails ... ok
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] entrypoint 'oak_main' export has incorrect function signature: Signature { params: [I64, I32, I32, I32, I32, I32, I32], return_type: Some(I32) }
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] could not validate entrypoint: ErrInvalidArgs
[2020-09-10T20:47:15Z WARN  oak_runtime] could not create node: IncorrectWebAssemblyModuleName
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Err(ErrInvalidArgs)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9155368652591746135)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9155368652591746135) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 9360967439716317465 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 9360967439716317465 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::wasm::tests::wasm_starting_module_with_wrong_signature_fails ... ok
[2020-09-10T20:47:15Z INFO  oak_runtime::node::wasm] entrypoint 'oak_main' export validated
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::wasm] Wasm module SHA-256 hash: [26, 161, 141, 245, 243, 77, 146, 104, 219, 10, 136, 14, 100, 21, 76, 8, 240, 205, 105, 95, 72, 171, 239, 72, 123, 153, 124, 126, 132, 34, 230, 115]
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): new ABI handle 4251925570913386371 maps to Channel 0 READ
[2020-09-10T20:47:15Z INFO  oak_runtime] NodeId(0): start node instance NodeId(1) with privilege NodePrivilege { can_declassify_confidentiality_tags: {Tag { tag: Some(WebAssemblyModuleTag(WebAssemblyModuleTag { web_assembly_module_hash_sha_256: [26, 161, 141, 245, 243, 77, 146, 104, 219, 10, 136, 14, 100, 21, 76, 8, 240, 205, 105, 95, 72, 171, 239, 72, 123, 153, 124, 126, 132, 34, 230, 115] })) }}, can_endorse_integrity_tags: {Tag { tag: Some(WebAssemblyModuleTag(WebAssemblyModuleTag { web_assembly_module_hash_sha_256: [26, 161, 141, 245, 243, 77, 146, 104, 219, 10, 136, 14, 100, 21, 76, 8, 240, 205, 105, 95, 72, 171, 239, 72, 123, 153, 124, 126, 132, 34, 230, 115] })) }} }
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(5932870466176810717)
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::wasm] test: running entrypoint 'oak_main'
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(5932870466176810717) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 490605741076439707 => Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(1) handle 4251925570913386371 => Channel 0 READ
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping node NodeId(1) ...
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node test(1)...
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] entrypoint 'oak_main' export not found
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] entrypoint 'oak_other_main' export not found
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] could not validate entrypoint: ErrInvalidArgs
[2020-09-10T20:47:15Z WARN  oak_runtime] could not create node: IncorrectWebAssemblyModuleName
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] could not validate entrypoint: ErrInvalidArgs
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Err(ErrInvalidArgs)
[2020-09-10T20:47:15Z WARN  oak_runtime] could not create node: IncorrectWebAssemblyModuleName
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(244963718117020840)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_other_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Err(ErrInvalidArgs)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(244963718117020840) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9092960943208256323)
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(9092960943208256323) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 16698263373585990938 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime::node::wasm] entrypoint 'oak_main' export validated
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 16096544177349775597 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 16698263373585990938 => Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 16096544177349775597 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::wasm] Wasm module SHA-256 hash: [26, 161, 141, 245, 243, 77, 146, 104, 219, 10, 136, 14, 100, 21, 76, 8, 240, 205, 105, 95, 72, 171, 239, 72, 123, 153, 124, 126, 132, 34, 230, 115]
test node::wasm::tests::wasm_starting_module_missing_an_export_fails ... ok
test node::wasm::tests::wasm_starting_module_with_wrong_export_fails ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): new ABI handle 5475638980536319391 maps to Channel 0 READ
[2020-09-10T20:47:15Z INFO  oak_runtime] NodeId(0): start node instance NodeId(1) with privilege NodePrivilege { can_declassify_confidentiality_tags: {Tag { tag: Some(WebAssemblyModuleTag(WebAssemblyModuleTag { web_assembly_module_hash_sha_256: [26, 161, 141, 245, 243, 77, 146, 104, 219, 10, 136, 14, 100, 21, 76, 8, 240, 205, 105, 95, 72, 171, 239, 72, 123, 153, 124, 126, 132, 34, 230, 115] })) }}, can_endorse_integrity_tags: {Tag { tag: Some(WebAssemblyModuleTag(WebAssemblyModuleTag { web_assembly_module_hash_sha_256: [26, 161, 141, 245, 243, 77, 146, 104, 219, 10, 136, 14, 100, 21, 76, 8, 240, 205, 105, 95, 72, 171, 239, 72, 123, 153, 124, 126, 132, 34, 230, 115] })) }} }
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::wasm] test: running entrypoint 'oak_main'
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Ok(())
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(14154969170481411718)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(14154969170481411718) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 10859620126471780718 => Channel 0 WRITE
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(1) handle 5475638980536319391 => Channel 0 READ
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping node NodeId(1) ...
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node test(1)...
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] entrypoint 'oak_main' export has incorrect function signature: Signature { params: [I64], return_type: Some(I32) }
[2020-09-10T20:47:15Z WARN  oak_runtime::node::wasm] could not validate entrypoint: ErrInvalidArgs
[2020-09-10T20:47:15Z WARN  oak_runtime] could not create node: IncorrectWebAssemblyModuleName
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): node_create(NodeConfiguration { name: "test", config_type: Some(WasmConfig(WebAssemblyConfiguration { wasm_module_name: "oak_module", wasm_entrypoint_name: "oak_main" })) }, Label { confidentiality_tags: [], integrity_tags: [] }) -> Err(ErrInvalidArgs)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(580815582432483639)
[2020-09-10T20:47:15Z DEBUG oak_runtime::proxy] NodeId(0): channel_close(580815582432483639) -> Ok(())
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 1767916906041923217 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 1767916906041923217 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::wasm::tests::wasm_starting_module_with_wrong_signature_3_fails ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::wasm] test: entrypoint 'oak_main' completed
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: [4251925570913386371]
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node test(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping node NodeId(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 490605741076439707 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::wasm::tests::wasm_verify_module_signature_succeeds ... ok
[2020-09-10T20:47:15Z DEBUG oak_runtime::node::wasm] test: entrypoint 'oak_main' completed
[2020-09-10T20:47:15Z DEBUG oak_runtime] NodeId(1): remove_node_id() found open handles on exit: [5475638980536319391]
[2020-09-10T20:47:15Z DEBUG oak_runtime] join thread for node test(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping node NodeId(1)...done
[2020-09-10T20:47:15Z INFO  oak_runtime] stopping runtime instance
[2020-09-10T20:47:15Z DEBUG oak_runtime] waking waiters on NodeId(0) handle 10859620126471780718 => Channel 0 WRITE
[2020-09-10T20:47:15Z INFO  oak_runtime] Runtime instance dropped
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] last writer for channel 0 gone, wake waiters
[2020-09-10T20:47:15Z DEBUG oak_runtime::channel] dropping Channel object Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
[2020-09-10T20:47:15Z ERROR oak_runtime::channel] Couldn't send ChannelDestroyed event, since the runtime has been dropped. Channel { id=0, #readers=0, #writers=0, label=Label { confidentiality_tags: [], integrity_tags: [] } }
test node::wasm::tests::wasm_starting_minimal_module_succeeds ... ok

```

</p>
</summary>

_Originally posted by @tiziano88 in https://github.com/project-oak/oak/pull/1461#issuecomment-690563634_

### PR DESCRIPTION
**Pull request by rbehjati**
Fixes #1462

### CODE REVIEW

File: oak_runtime/src/node/http/tests.rs [hunk 1]
```diff
@@ -244,12 +265,30 @@ async fn send_request(
...
-        .unwrap();
-
-    client.request(request).await
+    // The client thread may start sending the requests before the server is up. In this case, the
+    // request will be rejected with a "ConnectError". To make the tests are stable, we need to
+    // retry sending the requests until the server is up. To distinguish between these cases and
+    // actual errors (e.g., errors due to invalid TLS certificates), we need to check the cause of
+    // the error.
+    loop {
+        let request = hyper::Request::builder()
```
Comment (tiziano88) [inline oak_runtime/src/node/http/tests.rs:274]: This logic seems very coupled with the actual testing logic now, and also since requests may not be idempotent, it seems a bit risky to just keep retrying. 

Have you considered a different approach, in which *before* sending the actual request, the client performs some other sort of health check? that may be just sending a [`CONNECT`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) request until it succeeds, and then send the actual request for test after that. Alternatively expose another endpoint (e.g. `/status` or `/health`, not sure what's the convention) that returns a value when the server is up. Presumably we will need that for proper cloud deployments too anyways, right?

File: oak_runtime/src/node/http/tests.rs [hunk 2]
```diff
@@ -30,7 +30,7 @@ struct HttpServerTester {
 }
 
 impl HttpServerTester {
-    fn new(port: u32, with_simulator_thread: bool) -> HttpServerTester {
+    fn new(port: u32, number_of_requests: i32) -> HttpServerTester {
```
Comment (tiziano88) [inline oak_runtime/src/node/http/tests.rs:33]: Could you document this parameter?

File: oak_runtime/src/node/http/tests.rs [hunk 3]
```diff
@@ -197,22 +211,29 @@ fn create_communication_channel(runtime: &RuntimeProxy) -> (oak_abi::Handle, oak
...
-        body: vec![],
-        status: http::status::StatusCode::OK.as_u16() as i32,
-        headers: hashmap! {},
-    };
-    invocation
-        .sender
-        .expect("Empty sender on invocation.")
-        .send(resp, runtime)
-        .unwrap();
+// Simulate an Oak node that responds to the specified number of requests.
```
Comment (tiziano88) [inline oak_runtime/src/node/http/tests.rs:214]: Not sure what this means exactly, is it that it only accepts this many requests and then fails for any subsequent request?

File: oak_runtime/src/node/http/tests.rs (hunk 2 above)
Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:36]: Done.

File: oak_runtime/src/node/http/tests.rs (hunk 3 above)
Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs]: I have extended the comment with more explanations.
It does not fail. Either the server thread or the client thread will block for ever if the number of expected requests does not match the number of requests sent. As I have explained in the comment, the node simulator could alternatively listen for incoming requests in an infinite loop and have a termination mechanism to signal the end of the test from outside. But I think, specifying the exact number of expected requests is more appropriate for testing.

File: oak_runtime/src/node/http/tests.rs (hunk 1 above)
Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:281]: I don't see how `CONNECT` would help. We would still need to retry on that. In general, retrying should be part of any robust interaction with the server, so in my opinion the coupling is normal. 

What do you mean by idempotent "request"? Please note that this is not the general HTTP server pseudo node logic Tis is just a specific test. The GET method that is called here is idempotent (is not it? It does not do anything really!). Moreover, the tests do not discard the actual responses they get from the server. So, it would not be a problem even if the GET method used in the tests was not idempotent. 

Exposing another endpoint would still require the same retrying logic, but for the health check endpoint. So, again I don't see how that could have any impact apart from making the tests unnecessarily complicated and diverted from the important scenario that needs to be tested. 

Also, please note that the health check endpoints should be added by each Oak node connected to an HTTP server pseudo node separately, and what we have here is just a test. We could perhaps modify HTTP server pseudo node to add those endpoints by default or if configured to do so. That would address the cloud deployment need for it, but is out of the scope of this test.

File: oak_runtime/src/node/http/tests.rs [hunk 4]
```diff
@@ -244,12 +273,30 @@ async fn send_request(
...
+            .header(oak_abi::OAK_LABEL_HTTP_PROTOBUF_KEY, label_bytes.clone())
+            .body(hyper::Body::empty())
+            .unwrap();
+
+        match client.request(request).await {
+            Ok(reps) => return Ok(reps),
+            Err(error) => {
+                // We cannot access the cause of the error, so we need to check the string instead.
+                let error_str = format!("{:?}", error);
+                if error_str.contains("ConnectError") {
```
Comment (tiziano88) [inline oak_runtime/src/node/http/tests.rs:294]: Could you add a link to https://github.com/hyperium/hyper/blob/6e7e4e2cd50197fe2edda22d1646b89b1f6513b3/src/client/connect/http.rs#L425-L436 or wherever this string is coming from, so that if things start failing in the future because of some upstream change, we know how to fix it?

Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:307]: Done.

File: oak_runtime/src/node/http/tests.rs [hunk 5]
```diff
@@ -197,35 +221,39 @@ fn create_communication_channel(runtime: &RuntimeProxy) -> (oak_abi::Handle, oak
...
-    };
-    invocation
-        .sender
-        .expect("Empty sender on invocation.")
-        .send(resp, runtime)
-        .unwrap();
+// Simulate an Oak node that responds to the specified number of requests. Since the Oak node blocks
+// until a new request is received, we need to know the number of requests that the test sends
+// beforehand. Alternatively, the node simulator could listen for incoming requests in an infinite
+// loop and have a termination mechanism that could be signalled from outside. However, specifying
```
Comment (tiziano88) [inline oak_runtime/src/node/http/tests.rs:227]: Since it's reading from a channel, why not just read from the channel until the channel is exhausted, which is what we normally do in the actual nodes? Then the signal to terminate would be closing the channel.

File: oak_runtime/src/node/http/tests.rs [hunk 6]
```diff
@@ -197,35 +221,39 @@ fn create_communication_channel(runtime: &RuntimeProxy) -> (oak_abi::Handle, oak
...
+fn oak_node_simulator(
+    number_of_requests: i32,
+    runtime: &RuntimeProxy,
+    invocation_receiver: oak_abi::Handle,
+) {
+    for _counter in 0..number_of_requests {
+        // Get invocation message that contains the response_writer handle.
+        let invocation_receiver = Receiver::<HttpInvocation>::new(ReadHandle {
+            handle: invocation_receiver,
+        });
```
Comment (tiziano88) [inline oak_runtime/src/node/http/tests.rs:238]: This seems like it should be created once and for all before the loop?

File: oak_runtime/src/node/http/tests.rs (hunk 1 above)
Comment (tiziano88) [reply oak_runtime/src/node/http/tests.rs:292]: Thanks for the detailed reply, I learned a few things from it.

> This does not generally guarantee a robust behaviour. Even if the health check request is successful, there is no guarantee that the server will remain up and running for the next request. In a robust application each request must be retried regardless of the status from the health check or previous requests to the server. The scenario you have described is not realistic, and I think it is better to simulate a realistic scenario in the test.

Note that we don't expect flakiness during test, so retrying requests just in case they fail because the server went down again seems like something we would want to fail on, rather than have retrying logic around. I still think what I described is realistic for a test: wait until the server is up (before performing any request), then expect that every subsequent request gets served correctly at the first try.

> This is not true. The retry loop does not retry the entire test logic, it only retries sending the request, which as described above is what is needed to be done in reality. I have now moved the creation of the client out of send_request. So it should be clearer that the retry loop only retries sending the request.

Does this imply that for any HTTP request done by a real client, it should always be retried in a loop because it may fail?

File: oak_runtime/src/node/http/tests.rs (hunk 2 above)
Comment (tiziano88) [reply oak_runtime/src/node/http/tests.rs:37]: It may not make sense to repeat it, but I think it makes sense to have a comment saying where to look, if someone were looking at the documentation of this method (as opposed to reading through its implementation).

**Review by tiziano88 — APPROVED** [review]

File: oak_runtime/src/node/http/tests.rs (hunk 6 above)
Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs]: Thanks. Done.

File: oak_runtime/src/node/http/tests.rs (hunk 1 above)
Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:293]: > Does this imply that for any HTTP request done by a real client, it should always be retried in a loop because it may fail?

Yes. It should be fixed in the rust client in `http_server` too, but in a different PR. Hyper's `client::request` already retries sending the request, but retries on other types of errors.

File: oak_runtime/src/node/http/tests.rs (hunk 5 above)
Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:227]: I don't know what signals the exhaustion of the channel. Do you have a code example? 
The documentation of `receive` only says "**Waits, reads and decodes a message from the [`Receiver::handle`].**". This documentation must be extended with details like the channel exhaustion, error conditions, and example usage.

Comment (tiziano88) [reply oak_runtime/src/node/http/tests.rs:227]: I don't have the details at hand, but roughly something like this:

https://github.com/project-oak/oak/blob/984b3660a9bd9e551547d40c5314517011c22f36/oak_runtime/src/node/logger.rs#L58-L91

Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:227]: I tried with an infinite loop that terminates in case of any error, but it blocks for ever. What is signalling the end of the channel?

File: oak_runtime/src/node/http/tests.rs (hunk 1 above)
Comment (tiziano88) [reply oak_runtime/src/node/http/tests.rs:293]: ah nice, I didn't know that!

File: oak_runtime/src/node/http/tests.rs (hunk 5 above)
Comment (tiziano88) [reply oak_runtime/src/node/http/tests.rs:227]: It should be signalled by closing the channel on the other side, or the runtime terminating. Maybe neither of these things is happening in tests though.

Comment (rbehjati) [reply oak_runtime/src/node/http/tests.rs:227]: I think the problem is that the nodes in the test are not created by the runtime (not via `Runtime::`). I'll see if I can fix that, in another PR.
